// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7_-MPr7t6tTXEnh9moWM6bF_huNh2ZZU',
    appId: '1:508881276653:android:a421fecfddc8857c9d86e4',
    messagingSenderId: '508881276653',
    projectId: 'sovo-zadanie',
    storageBucket: 'sovo-zadanie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXb5A2ss9c9TZo0Sl665tVcTVMAMpnhBw',
    appId: '1:508881276653:ios:ca504ce16b8017559d86e4',
    messagingSenderId: '508881276653',
    projectId: 'sovo-zadanie',
    storageBucket: 'sovo-zadanie.appspot.com',
    iosClientId: '508881276653-l2d8s8v8krkuaib36742c2ss1l4b6qoi.apps.googleusercontent.com',
    iosBundleId: 'com.malgorzatamyslicka.sovoZadanie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXb5A2ss9c9TZo0Sl665tVcTVMAMpnhBw',
    appId: '1:508881276653:ios:ca504ce16b8017559d86e4',
    messagingSenderId: '508881276653',
    projectId: 'sovo-zadanie',
    storageBucket: 'sovo-zadanie.appspot.com',
    iosClientId: '508881276653-l2d8s8v8krkuaib36742c2ss1l4b6qoi.apps.googleusercontent.com',
    iosBundleId: 'com.malgorzatamyslicka.sovoZadanie',
  );
}
